version: '3.8'

services:
  judge:
    build:
      context: ./docker/dev/judge
      dockerfile: Dockerfile
    image: judge-env
    container_name: judge
    volumes:
      - ./judge:/judge
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    networks:
      - backend

networks:
  backend:
    driver: bridge