version: '2.1'
services:
  judge-env:
    build:
      context: ./judge
      dockerfile: Dockerfile
    image: judge-env:latest
    container_name: forest-ce-judge-env
    restart: unless-stopped
    volumes:
      - "judge-volume:/judge"
    environment:
      - TZ=Asia/Shanghai
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
volumes:
  judge-volume:
